# Generated by Django 6.0.6 on 2026-06-19 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Telefon +998 bilan boshlanishi kerak', regex='^\\+998\\d{9}$')])),
                ('project_opinion', models.TextField()),
            ],
        ),
    ]
