# Generated by Django 6.0.6 on 2026-06-24 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_category_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqamni +998901234567 ko'rinishida kiriting.", regex='^\\+998\\d{9}$')]),
        ),
    ]
